# Generated by Django 2.2 on 2019-11-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='late',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='registered_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='submission_date',
        ),
        migrations.AlterField(
            model_name='standard',
            name='objective_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='standard',
            name='standard_code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='standard',
            name='standard_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='standard',
            name='standard_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='standard',
            name='strand_code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='standard',
            name='strand_description',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Assigned', 'Assigned'), ('Incomplete', 'Incomplete'), ('Exempt', 'Exempt')], max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=0)),
                ('registered_datetime', models.DateTimeField(auto_now=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygrades.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygrades.Student')),
            ],
            options={
                'verbose_name_plural': 'Student Assignments',
            },
        ),
    ]
