# Generated by Django 2.2 on 2019-11-07 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0002_auto_20191105_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='academic_semester',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='gradassign',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='level',
            field=models.CharField(choices=[('Core', 'Core'), ('Supplemental', 'Supplemental')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='loginurl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='recorded_from',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Automatic', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semesterend',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tracking',
            field=models.CharField(choices=[('Repeating Weekly', 'Repeating Weekly'), ('From Pacing List', 'From Pacing List')], default='Repeating Weekly', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
