# Generated by Django 2.2 on 2019-11-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0003_auto_20191107_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='required',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
