# Generated by Django 2.2 on 2019-11-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0004_auto_20191108_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
