# Generated by Django 2.2 on 2019-11-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0005_student_birthdate'),
        ('mygrades', '0005_studentassignment_enrollment'),
    ]

    operations = [
    ]
