# Generated by Django 2.2 on 2019-11-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0006_merge_20191109_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='syllabus',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zoom',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
