# Generated by Django 2.2 on 2019-11-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0006_merge_20191109_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='shown_in_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
