# Generated by Django 2.2 on 2019-11-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0007_studentassignment_shown_in_weekly'),
        ('mygrades', '0007_auto_20191110_1937'),
    ]

    operations = [
    ]
