# Generated by Django 2.2 on 2019-11-15 07:01

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Enrollment = apps.get_model("mygrades", "Enrollment")
    db_alias = schema_editor.connection.alias
    Enrollment.objects.using(db_alias).update(required="0")

class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0008_merge_20191112_1648'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='enrollment',
            name='required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Assigned', 'Assigned'), ('Incomplete', 'Incomplete'), ('Exempt', 'Exempt'), ('Complete', 'Complete')], max_length=30),
        ),
    ]
