# Generated by Django 2.2 on 2019-11-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0010_auto_20191118_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_attendance', to='mygrades.Enrollment'),
            preserve_default=False,
        ),
    ]
