# Generated by Django 2.2 on 2019-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0011_auto_20191118_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGradeBookReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('gradassign', 'gradassign'), ('progress-weekly', 'progress-weekly'), ('report-card-quarter', 'report-card-quarter')], max_length=32)),
                ('academic_semester', models.CharField(max_length=16)),
                ('quarter', models.CharField(blank=True, max_length=1)),
                ('week', models.CharField(blank=True, max_length=2)),
                ('semester', models.CharField(blank=True, max_length=1)),
            ],
        ),
    ]
