# Generated by Django 2.2 on 2019-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0013_auto_20191118_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebook',
            name='academic_semester',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentgradebookreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
