# Generated by Django 2.2 on 2019-11-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0015_auto_20191122_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradebook',
            name='complete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
