# Generated by Django 2.2.7 on 2019-11-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0019_auto_20191123_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='goog_calendar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='principal_email',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
