# Generated by Django 2.2 on 2019-11-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0020_auto_20191129_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='exemptassignment',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='mygrades.Assignment'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='principal_email',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
