# Generated by Django 2.2 on 2019-11-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0022_remove_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
